### PR TITLE
Add Api content Pull Request

### PR DESCRIPTION
**Pull request by tamoorsaeed22**
### Implementations in this project

- Used [axios] to make your HTTP requests to the backend
- Fetch your books from the Bookstore API after the component has rendered
- Refactor add book and remove book features to persist your changes in the server
- Application should behave the same way after the refactoring

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @tamoorsaeed22   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- NO linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to always add the `category` property in the newly added book object because your app only adds the first book successfully but when adding the second we receive this error message ` "'category' is required." `. Kindly fix that by making sure that every new is added as a category because the request for adding a book is being rejected.

  **_Hint: Make sure after dispatching the `addBook` action you are setting your `values` back to `template` instead of empty object which will always provides with empty `category`_**



   

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tamoorsaeed22** [comment]
@levy002 adds the first book successfully but when adding the second we receive this error message "'category' is required." is resolved and now when adding a book and need to another book so its working exactly demanded.

**Comment by levy002** [comment]
Hello @tamoorsaeed22, that's awesome mate. KIndly submit again your PR link for a second review. Keep rocking :rocket:

**Review by ishimwezachee — APPROVED** [review]
Hi @tamoorsaeed22 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
image
## Highlights
✅All linters are checked.
✅The right GitHub flow method has been used.
✅Professional pull request title and description

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
